[package]
name = "ggrs-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bincode = "1.3.3"
bytemuck = "1.13.0"
ggrs = "0.9.3"
pod = "0.5.0"
serde = {version = "1.0.152", features = ["derive"]}
